name: redfire_test
description: Utilities to simplify testing in apps that use redfire.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth:
  google_sign_in:
  sign_in_with_apple: ^3.3.0 # 3.2.0 â†’ 3.3.0 was a breaking change due to federation
  http:
  redux:
  mockito:
  freezed_annotation:
  json_annotation: ^4.4.0

  redfire:
    path: ../redfire

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable: