name: redfire
description: A redux based state management & navigation solution, with prebuilt modules for Firebase features.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple: ^3.3.0 # 3.2.0 â†’ 3.3.0 was a breaking change due to federation
  cloud_firestore:
  url_launcher:
  redux:
  flutter_redux:
  fast_immutable_collections:
  freezed_annotation:
  json_annotation: ^4.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
  test:
  mockito:
  redfire_test:
    path: ../redfire_test

flutter:  
  fonts:
    - family:  RedFireIcons
      fonts:
        - asset: packages/redfire/assets/RedFireIcons.ttf
        
  assets:
    - packages/redfire/assets/apple_white.png
    - packages/redfire/assets/google.png
    - packages/redfire/assets/github.png
